<a href="https://colab.research.google.com/github/GungunSinghal03/svm_diabetes_prediction/blob/main/implementing__svm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
import numpy as np

class SVM_classifier():

    def __init__(self, learning_rate, no_of_iterations, lambda_parameter):
        self.learning_rate = learning_rate
        self.no_of_iterations = no_of_iterations
        self.lambda_parameter = lambda_parameter

    def fit(self, X, Y):
        self.m, self.n = X.shape

        self.w = np.zeros(self.n)
        self.b = 0

        self.X = X
        self.Y = Y

        # Convert labels to -1 and 1
        self.y_label = np.where(self.Y <= 0, -1, 1)

        for _ in range(self.no_of_iterations):
            self.update_weights()

    def update_weights(self):
        for index, x_i in enumerate(self.X):

            condition = self.y_label[index] * (np.dot(x_i, self.w) + self.b) >= 1

            if condition:
                dw = 2 * self.lambda_parameter * self.w
                db = 0
            else:
                dw = 2 * self.lambda_parameter * self.w - self.y_label[index] * x_i
                db = -self.y_label[index]

            # update
            self.w = self.w - self.learning_rate * dw
            self.b = self.b - self.learning_rate * db

    def predict(self, X):
        output = np.dot(X, self.w) + self.b
        predicted_labels = np.sign(output)

        # Convert -1,1 → 0,1
        y_hat = np.where(predicted_labels <= -1, 0, 1)

        return y_hat

#Importing the dependencies

In [3]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

#Data collection

In [5]:
df=pd.read_csv('/content/diabetes.csv')

In [6]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [7]:
df.shape

(768, 9)

In [8]:


df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [9]:
df.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [10]:
df['Outcome'].value_counts()
#0-->non-diabetic
#1-->diabetic

Outcome
0    500
1    268
Name: count, dtype: int64

In [11]:
#separating the features and target
#when we are removing row-->axis=0,column-->axis=1
features=df.drop(columns='Outcome',axis=1)
target=df['Outcome']

In [12]:
print(features)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6
1              1       85             66             29        0  26.6
2              8      183             64              0        0  23.3
3              1       89             66             23       94  28.1
4              0      137             40             35      168  43.1
..           ...      ...            ...            ...      ...   ...
763           10      101             76             48      180  32.9
764            2      122             70             27        0  36.8
765            5      121             72             23      112  26.2
766            1      126             60              0        0  30.1
767            1       93             70             31        0  30.4

     DiabetesPedigreeFunction  Age
0                       0.627   50
1                       0.351   31
2                       0.672   32
3                       0.167   21
4                       2.288   33
..                        ...  ...
763                     0.171   63
764                     0.340   27
765                     0.245   30
766                     0.349   47
767                     0.315   23

[768 rows x 8 columns]

In [13]:
print(target)

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

#Data Standardization

In [14]:
scaler=StandardScaler()

In [15]:
scaler.fit(features)

StandardScaler()

In [16]:
standard_data=scaler.transform(features)

In [17]:
print(standard_data)

[[ 0.63994726  0.84832379  0.14964075 ...  0.20401277  0.46849198
   1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 ... -0.68442195 -0.36506078
  -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 ... -1.10325546  0.60439732
  -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075 ... -0.73518964 -0.68519336
  -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 ... -0.24020459 -0.37110101
   1.17073215]
 [-0.84488505 -0.8730192   0.04624525 ... -0.20212881 -0.47378505
  -0.87137393]]

In [18]:
features=standard_data
target=df['Outcome']

In [19]:
print(features)

[[ 0.63994726  0.84832379  0.14964075 ...  0.20401277  0.46849198
   1.4259954 ]
 [-0.84488505 -1.12339636 -0.16054575 ... -0.68442195 -0.36506078
  -0.19067191]
 [ 1.23388019  1.94372388 -0.26394125 ... -1.10325546  0.60439732
  -0.10558415]
 ...
 [ 0.3429808   0.00330087  0.14964075 ... -0.73518964 -0.68519336
  -0.27575966]
 [-0.84488505  0.1597866  -0.47073225 ... -0.24020459 -0.37110101
   1.17073215]
 [-0.84488505 -0.8730192   0.04624525 ... -0.20212881 -0.47378505
  -0.87137393]]

In [20]:
print(target)

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

#Splitting the data into training and testing data

In [21]:
X_train,X_test,Y_train,Y_test=train_test_split(features,target,test_size=0.2,random_state=2)

In [22]:
print(features.shape,X_train.shape,X_test.shape)

(768, 8) (614, 8) (154, 8)

#Training the model-SVM classifier

In [23]:
classifier=SVM_classifier(learning_rate=0.001,no_of_iterations=1000,lambda_parameter=0.01)

In [24]:





#training the svm classifier with training data
classifier.fit(X_train,Y_train)

#Model Evaluation

In [25]:
#accuracy on training data
X_train_prediction=classifier.predict(X_train)
training_data_accuracy=accuracy_score(Y_train,X_train_prediction)

In [26]:
print('Accuracy on training data using SVM is: ',training_data_accuracy)

Accuracy on training data using SVM is:  0.7768729641693811

In [27]:
#accuracy on test data
X_test_prediction=classifier.predict(X_test)
testing_data_accuracy=accuracy_score(Y_test,X_test_prediction)

In [28]:
print(testing_data_accuracy)

0.7532467532467533

#Building a predictive system

In [31]:
input_data=(5,166,72,19,175,25.8,0.587,51)
#change the input data into numpy array
input_data_as_array=np.asarray(input_data)
#reshape the array
input_data_reshape=input_data_as_array.reshape(1,-1)
#standardizing the input data
std_data=scaler.transform(input_data_reshape)
print(std_data)
prediction=classifier.predict(std_data)
print(prediction)

[[ 0.3429808   1.41167241  0.14964075 -0.09637905  0.82661621 -0.78595734
   0.34768723  1.51108316]]
[1]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [32]:
if (prediction[0]==0):
  print("The person is diabetic")
else: print("The person is not diabetic")

The person is not diabetic